### ISSUE TITLE
Feature request: FATE dice support

### ISSUE THREAD

**Issue by SupernaviX** [Burn-E99/TheArtificer#1]
Hi! 

Would you be willing to support the [FATE dice](https://help.roll20.net/hc/en-us/articles/360037773133-Dice-Reference#DiceReference-FATEDice) syntax from Roll20? They're essentially 6-sided dice where two sides are -1, two sides are 0, and two sides are 1.  My group is using `[[4d3 - 8 + <bonus>]]` to get the same results, but it'd be nice to be able to use`[[4dF + <bonus>]]` directly.

**Comment by Burn-E99** [comment]
Heyo!  Thanks for using The Artificer!

There are plans for supporting the full Roll20 syntax (including the FATE dice) in version 1.5 of the bot.  I'll be getting started on development later today, with the hopes of having 1.5 ready to release sometime in the next week.

I'll be adding development plans to the README later today, along with a link to my support server (that I apparently forgot to add to the README in the first place, D'OH).

**Comment by SupernaviX** [comment]
Thanks for the quick response! (and the convenient dice roller of course)

**Comment by Burn-E99** [comment]
So, better late than never, but I finally got V2.0 of artificer complete, and it now supports FATE dice (`[[4dF]]`) and many other things (that can be found here: https://github.com/Burn-E99/TheArtificer/releases/tag/V2.0.0).
