### ISSUE TITLE
Can't seem to get the "useful flags" to work

### ISSUE THREAD

**Issue by mgoosh01** [Burn-E99/TheArtificer#2]
I'm just trying to use the flag "-o a" to order a group of d6 rolls, but it never seems to work.

When I do 
`[[5d6 o a]]`
I get an error, which makes sense. but any time it's placed after the brackets, it doesn't apply the flag and just has it as plain text after the roll total. See below:
![image](https://user-images.githubusercontent.com/31423941/118414005-2fd4ce00-b670-11eb-9b48-e80539928c7d.png)

What am I doing wrong?

**Comment by Burn-E99** [comment]
Better late than never, but with V2.0.0 of the bot now online, I should respond here.

The third format you tried was the closest, but you need a space before the `-o a`, example: `[[5d6]] -o a`.  Additionally, you need more than one roll to happen in the same message to fully utilize the ordering, such as `[[5d6]] [[5d6]] [[5d6]] [[5d6]] [[5d6]] -o a`.
